pt_bloom_simple: bin_dir pt_bloom_simple.c
	gcc -I ../../src pt_bloom_simple.c -L ../../bin -lprobability -o ../bin/pt_bloom_simple

.PHONY: bin_dir clean

bin_dir:
	mkdir -p ../bin/

clean: 
	rm -rf ../bin/
